### PR TITLE
Some changes I found useful when using this for posting feeds to twitter

### PR DESCRIPTION
**Pull request by hvoigt**
Hi,

I used your twitter gateway for sharing changes to a website to twitter. I did some changes to the code and extended the README with a setup description. Maybe this is helpful for others.

See the individual commits about a description.

Cheers Heiko

### CODE REVIEW

**Review by mpirnat — CHANGES_REQUESTED** [review]
The entire purpose of this project was literally so that I could use my vanity shortener, so I'd prefer not to have custom shortening removed. Otherwise I'd just set up an IFTTT recipe. Maybe there's a way it could be optional?

**Comment by mpirnat** [comment]
I do want to say thanks for sending a pull request, and I'm glad that this has been useful for you. I'm overall positive on these changes and will merge if we can keep the shortening somehow.

**Comment by hvoigt** [comment]
I will have a look into that. It should not be that hard to keep the shortening. Maybe something like: "if there is no shortener url configured we do not use it".

I just discovered that the problem with non-ascii characters is not completely solved. Since I just got an error for another post. I will have to look into that as well.

Will send an updated pull request once that is done. Might take some days since it is only a hobby project I use this for.

**Comment by mpirnat** [comment]
No worries, it's a hobby project for me too, that I haven't touched in a long time. I was honestly surprised anyone else had seen it, let alone used it! :-)

**Comment by hvoigt** [comment]
I finally got around looking into this. So now I only use the fixed twitter URL shortening for calculation if there is no custom shortener configured. I also added another commit on top which uploads images from the feed to twitter. (Thats why I got around looking into it again :))

Have a look (and test it) if this would also fit your needs.

Cheers Heiko

**Comment by hvoigt** [comment]
This is old lets close it.

**Pull request closed without merging**
